language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - sudo /usr/bin/pip3 install black
install:
  - pip install -r requirements.txt
script:
  - /usr/bin/black --check matplotboard
