language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - git clone https://github.com/psf/black.git
script:
  - ls -l `which python`
  - python black/black.py --check matplotboard
